### PR TITLE
solution

### PR DESCRIPTION
**Pull request by olenitut**
[DEMO LINK](https://olenitut.github.io/react_todo-app-loading-todos/)

### CODE REVIEW

**Review by OlEzhA0 — CHANGES_REQUESTED** [review]
1. When I add todo and click `Enter`, page refreshes and my todo not added
2. I can't remove item
3. I can't complete item

**Comment by olenitut** [comment]
what you wrote here was not part of this task. Please, read the readme file for task guidelines

**Comment by olenitut** [comment]
how come you didn't chek it? ((

**Review by nazarmatsevych — APPROVED** [review]
Good work, just small suggestion which you could fix in this or next tasks

**Pull request closed without merging**
